library (pbdMPI, quietly=TRUE)
init()
table<-read.csv('http://archive.ics.uci.edu/ml/machine-learning-databases/00265/CASP.csv', sep=",")
table<-as.numeric(unlist(table))
table<-matrix(table, ncol=10)
N<-allreduce(nrow(table), op="sum")
mu<-allreduce(colSums(table)/N, op="sum")
table<-sweep(table, STATS=mu, MARGIN=2)
Cov.X<-allreduce(crossprod(table), op="sum")/(N-1)
comm.print(Cov.X)
